---
kind: pipeline
name: master

steps:
  - name: build-server
    image: plugins/docker
    settings:
      tags: ${DRONE_COMMIT_SHA:0:8}
      dockerfile: ./docker/Dockerfile.server
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: tests
    image: alpine
    commands:
      - echo "test-example"

  - name: build
    image: alpine
    commands:
      - echo "build-exampffffffle"

  - name: staging
    image: alpine
    commands:
      - echo "staging-example"

trigger:
  event:
    - merge
    - push
  branch:
    - master
---
kind: pipeline
name: pr

sfs:
  - name: tests
    image: alpine
    commands:
      - echo "test-example13"
      - printenv
trigger:
  event:
    - pull_request

---
kind: pipeline
name: switch

steps:
  - name: switch
    image: alpine
    commands:
      - echo "switched"
    when:
      target: switch

trigger:
  event:
    - promote
