---
kind: pipeline
name: master

steps:
  - name: tests
    image: alpine
    commands:
      - echo "test-example"

  - name: build
    image: alpine
    commands:
      - echo "build-exampffffffle"

  - name: staging
    image: alpine
    commands:
      - echo "staging-example"
    depends_on: [ tests, build ]

trigger:
  event:
    - merge
    - push
  branch:
    - master
---
kind: pipeline
name: pr

sfs:
  - name: tests
    image: alpine
    commands:
      - echo "test-example13"
      - printenv
trigger:
  event:
    - pull_request

---
kind: pipeline
name: switch

steps:
  - name: switch
    image: alpine
    commands:
      - echo "switched"
    when:
      target: switch

trigger:
  event:
    - promote
