---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: drone-server
  namespace: cicd
  labels:
    app: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone
  template:
    metadata:
      labels:
        app: drone
        type: server
      annotations:
        backup.ark.heptio.com/backup-volumes: drone-data-volume
    spec:
      serviceAccountName: drone
      volumes:
        - name: drone-data-volume
          persistentVolumeClaim:
            claimName: drone-claim
      containers:
        - name: drone-server
          image: drone/drone:1.0.0-rc.2
          imagePullPolicy: Always
          env:
            - name: DRONE_GIT_ALWAYS_AUTH
              value: "false"
            - name: DRONE_GITHUB_SERVER
              value: "https://github.com"
            - name: DRONE_GITHUB_CLIENT_ID
              value: "20d5b4e1ffd3238eef1e"
            - name: DRONE_GITHUB_CLIENT_SECRET
              value: "b11d56c5d18239d52f263f0d7c6cd821154f32c6"
            - name: DRONE_RPC_SECRET
              value: "123"
            - name: DRONE_SERVER_HOST
              value: "vorax.serveo.net"
            - name: DRONE_SERVER_PROTO
              value: "http"
            - name: DRONE_SERVER_PORT
              value: ":80"
            - name: DRONE_TLS_AUTOCERT
              value: "false"
            - name: DRONE_USER_CREATE
              value: "username:GoingFast,machine:false,admin:true,token:6457a26d2e804097e9a228bc4287f975"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: drone-data-volume
              mountPath: /var/lib/drone
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-claim
  namespace: cicd
spec:
  storageClassName: standard
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: drone-server
  namespace: cicd
spec:
  selector:
    app: drone
    type: server
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 32015
    - name: https
      targetPort: 443
      port: 443
      nodePort: 32016
