---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: alpine
inputs:
  - name: repository
run:
  path: /bin/sh
  args: ["-exc", "cd repository && go tests ./... -mod=vendor"]
