version: 2
jobs:
  staging:
    working_directory: $HOME
    docker:
      - image: dtzar/helm-kubectl
    steps:
      - checkout
      - run:
          name: Setup kubectl
          command: ./kubectl-context.sh
workflows:
  version: 2
  my-workflow:
    jobs:
      - test-kube-connection:
          context: k8s
